export const SEED_DATA = {
  users: [
    { id: 'usr-admin-101', name: 'Alexander Pierce', email: 'admin@erp.com', role: 'ADMIN' },
    { id: 'usr-sales-102', name: 'Rahul Sharma', email: 'sales@erp.com', role: 'SALES' },
    { id: 'usr-wh-103', name: 'Neha Patel', email: 'warehouse@erp.com', role: 'WAREHOUSE' },
    { id: 'usr-acc-104', name: 'Amit Verma', email: 'accounts@erp.com', role: 'ACCOUNTS' },
  ],
  customers: [
    {
      id: 'cust-101',
      name: 'ABC Traders',
      mobile: '+91 98765 43210',
      email: 'contact@abctraders.com',
      businessName: 'ABC Wholesale Logistics',
      gstNumber: '27AAAAA0000A1Z5',
      customerType: 'WHOLESALE',
      address: 'Plot 45, MIDC Industrial Area, Mumbai',
      status: 'ACTIVE',
      followUpDate: '2026-05-20T00:00:00.000Z',
      notes: 'Key distributor for Western Region',
      isActive: true,
    },
    {
      id: 'cust-102',
      name: 'XYZ Store',
      mobile: '+91 98123 45678',
      email: 'info@xyzstore.com',
      businessName: 'XYZ Supermarket Chain',
      gstNumber: '07BBBBB1111B1Z2',
      customerType: 'RETAIL',
      address: 'Shop 12, Main Market, Delhi',
      status: 'LEAD',
      followUpDate: '2026-05-21T00:00:00.000Z',
      notes: 'Interested in buying bulk USB accessories',
      isActive: true,
    },
    {
      id: 'cust-103',
      name: 'PQR Distributors',
      mobile: '+91 97654 32109',
      email: 'sales@pqrdistributors.in',
      businessName: 'PQR National Supply Corp',
      gstNumber: '29CCCCC2222C1Z8',
      customerType: 'DISTRIBUTOR',
      address: 'Electronic City Phase 1, Bengaluru',
      status: 'ACTIVE',
      followUpDate: '2026-05-22T00:00:00.000Z',
      notes: 'Monthly bulk orders executed on 15th',
      isActive: true,
    },
    {
      id: 'cust-104',
      name: 'LMN Retailers',
      mobile: '+91 96543 21098',
      email: 'orders@lmnretail.com',
      businessName: 'LMN Retail Outlets',
      gstNumber: '33DDDDD3333D1Z4',
      customerType: 'RETAIL',
      address: 'Anna Salai, Chennai',
      status: 'INACTIVE',
      followUpDate: '2026-05-23T00:00:00.000Z',
      notes: 'Deactivated account due to payment delay',
      isActive: false,
    },
    {
      id: 'cust-105',
      name: 'Global Supplies',
      mobile: '+91 95432 10987',
      email: 'admin@globalsupplies.com',
      businessName: 'Global Tech & Spares Ltd',
      gstNumber: '19EEEEE4444E1Z1',
      customerType: 'DISTRIBUTOR',
      address: 'Salt Lake Sector 5, Kolkata',
      status: 'ACTIVE',
      followUpDate: '2026-05-24T00:00:00.000Z',
      notes: 'Special discounts on bulk mechanical keyboards',
      isActive: true,
    },
  ],
  products: [
    {
      id: 'prod-201',
      name: 'USB Cable Type-C (2m)',
      sku: 'SKU-USB-001',
      category: 'Cables & Adapters',
      price: '500.00',
      stock: 150,
      minimumStock: 10,
      warehouse: 'Main Warehouse A',
      isActive: true,
    },
    {
      id: 'prod-202',
      name: 'Wireless Optical Mouse',
      sku: 'SKU-MSE-002',
      category: 'Computer Peripherals',
      price: '1200.00',
      stock: 45,
      minimumStock: 10,
      warehouse: 'Main Warehouse A',
      isActive: true,
    },
    {
      id: 'prod-203',
      name: 'Mechanical Keyboard RGB',
      sku: 'SKU-KBD-003',
      category: 'Computer Peripherals',
      price: '3500.00',
      stock: 3,
      minimumStock: 5,
      warehouse: 'Main Warehouse B',
      isActive: true,
    },
    {
      id: 'prod-204',
      name: 'HDMI Cable 4K High-Speed',
      sku: 'SKU-HDM-004',
      category: 'Cables & Adapters',
      price: '750.00',
      stock: 2,
      minimumStock: 5,
      warehouse: 'Main Warehouse B',
      isActive: true,
    },
    {
      id: 'prod-205',
      name: 'USB Hub 4-Port Ultra Slim',
      sku: 'SKU-HUB-005',
      category: 'Computer Peripherals',
      price: '1499.00',
      stock: 80,
      minimumStock: 15,
      warehouse: 'Main Warehouse A',
      isActive: true,
    },
  ],
  challans: [
    {
      id: 'ch-401',
      challanNumber: 'CH-00123',
      customerName: 'ABC Traders',
      status: 'CONFIRMED',
      totalQuantity: 50,
      totalAmount: '45250.00',
      date: '2026-05-17',
    },
    {
      id: 'ch-402',
      challanNumber: 'CH-00122',
      customerName: 'XYZ Store',
      status: 'DRAFT',
      totalQuantity: 10,
      totalAmount: '12500.00',
      date: '2026-05-17',
    },
    {
      id: 'ch-403',
      challanNumber: 'CH-00121',
      customerName: 'PQR Distributors',
      status: 'CONFIRMED',
      totalQuantity: 2,
      totalAmount: '32100.00',
      date: '2026-05-16',
    },
    {
      id: 'ch-404',
      challanNumber: 'CH-00120',
      customerName: 'LMN Retailers',
      status: 'CANCELLED',
      totalQuantity: 5,
      totalAmount: '8750.00',
      date: '2026-05-16',
    },
  ],
  auditLogs: [
    {
      id: 'aud-501',
      action: 'USER_CREATED',
      entity: 'User',
      entityId: 'usr-sales-102',
      user: { name: 'Alexander Pierce' },
      details: { role: 'SALES', createdByAdmin: true },
      createdAt: '2026-05-17T10:00:00.000Z',
    },
    {
      id: 'aud-502',
      action: 'STOCK_IN',
      entity: 'Product',
      entityId: 'prod-201',
      user: { name: 'Neha Patel' },
      details: { quantityAdded: 200, warehouse: 'Main Warehouse A' },
      createdAt: '2026-05-17T11:30:00.000Z',
    },
    {
      id: 'aud-503',
      action: 'CHALLAN_CONFIRMED',
      entity: 'Challan',
      entityId: 'ch-401',
      user: { name: 'Rahul Sharma' },
      details: { challanNumber: 'CH-00123', totalAmount: 45250.00 },
      createdAt: '2026-05-17T14:15:00.000Z',
    },
  ],
};
